### ISSUE TITLE
Local Whisper change to faster-whisper-server

### ISSUE THREAD

**Issue by kissze** [felipem1210/freetalkbot#22]
Hello,

i have found a better implementation of local running whisper, which is compatible with OpenAI API.
Here it is: https://github.com/fedirz/faster-whisper-server/

It is also capable to do "live" transcription, so in the long run it will be interesting.

Cheers,
Zoltan

**Comment by felipem1210** [comment]
Fantastic. I will have a look after I come back from vacation. Thanks for sharing!!
